[build]
  builder = "maven"
  build_command = "./mvnw package -DskipTests"
  output_directory = "target"

[deploy]
  start_command = "java -jar target/backend-springboot-0.0.1-SNAPSHOT.jar"
  healthcheck_path = "/health"

[env]
  PORT = "8080"

[python]
  install_command = "pip install torch diffusers psutil"