# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ubc-fashion-studio-ai-backend-container

on:
  push:
    branches:
      - feature/main-backend-deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://gcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c4ede6201a2f4d2fa806a711b5e2b692 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6b39e3438c1c4b13a30aa0878263ab02 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gcr.io/${{ secrets.AzureAppService_ContainerUsername_c4ede6201a2f4d2fa806a711b5e2b692 }}/kanakamsasikalyan/fashion-studio-ai:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ubc-fashion-studio-ai-backend-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cd3b5cea7ae04d98b5ec98b644394921 }}
        images: 'gcr.io/${{ secrets.AzureAppService_ContainerUsername_c4ede6201a2f4d2fa806a711b5e2b692 }}/kanakamsasikalyan/fashion-studio-ai:${{ github.sha }}'