# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ubc-fashion-studio-ai-backend

on:
  push:
    branches:
      - feature/main-backend-deployment
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'ubc-fashion-studio-ai-backend'
  AZURE_WEBAPP_SLOT: 'production'
  CONTAINER_REGISTRY: 'ghcr.io'
  CONTAINER_USERNAME: ${{ secrets.AzureAppService_ContainerUsername_471cceedd7fa4c44955901bad9519b38 }}
  CONTAINER_PASSWORD: ${{ secrets.AzureAppService_ContainerPassword_9bbf5c01358043038f88a791959a6c93 }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set lowercase REPO_NAME
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io/
          username: ${{ env.CONTAINER_USERNAME }}
          password: ${{ env.CONTAINER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ env.CONTAINER_USERNAME }}/kanakamsasikalyan/fashion-studio-ai:${{ github.sha }}
          file: ./Dockerfile

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_8542be066ca04aa385b99143408e2c89 }}
          images: ghcr.io/${{ env.CONTAINER_USERNAME }}/kanakamsasikalyan/fashion-studio-ai:${{ github.sha }}